DROP TABLE IF EXISTS Product_Category;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Saved_Search;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS User_Role;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Address;
